from geopy.distance import vincenty

newport_ri = (41.49008, -71.312796)
cleveland_oh = (41.499498, -81.695391)
print(vincenty(newport_ri, cleveland_oh).miles)

airportlist = [

    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '68.891(E)',
        'ICAO': None,
        'Latitude': '23.222(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': 'Keshod',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Keshod',
        'IATA': 'IXK',
        'Longitude': '70.270(E)',
        'ICAO': 'VAKS',
        'Latitude': '21.317(N)',
        'FAA': None,
        'MaxRunway': '4500ft'
    },
    {
        'City': 'Jaisalmer',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Jaisalmer',
        'IATA': 'JSA',
        'Longitude': '70.865(E)',
        'ICAO': 'VIJR',
        'Latitude': '26.889(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '71.482(E)',
        'ICAO': 'VIUT',
        'Latitude': '25.813(N)',
        'FAA': None,
        'MaxRunway': '9002ft'
    },
    {
        'City': 'Agatti Island',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': 'AGX',
        'Longitude': '72.176(E)',
        'ICAO': 'VOAT',
        'Latitude': '10.824(N)',
        'FAA': None,
        'MaxRunway': '4235ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '72.204(E)',
        'ICAO': 'VADS',
        'Latitude': '24.268(N)',
        'FAA': None,
        'MaxRunway': '3300ft'
    },
    {
        'City': 'Surat',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Surat',
        'IATA': 'STV',
        'Longitude': '72.742(E)',
        'ICAO': 'VASU',
        'Latitude': '21.114(N)',
        'FAA': None,
        'MaxRunway': '3600ft'
    },
    {
        'City': 'Daman',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Daman',
        'IATA': 'NMB',
        'Longitude': '72.843(E)',
        'ICAO': 'VADN',
        'Latitude': '20.434(N)',
        'FAA': None,
        'MaxRunway': '5909ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '73.103(E)',
        'ICAO': None,
        'Latitude': '26.436(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Ratnagiri',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Ratnagiri',
        'IATA': 'RTC',
        'Longitude': '73.328(E)',
        'ICAO': 'VARG',
        'Latitude': '17.014(N)',
        'FAA': None,
        'MaxRunway': '4500ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '73.711(E)',
        'ICAO': None,
        'Latitude': '27.208(N)',
        'FAA': None,
        'MaxRunway': '3853ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '73.904(E)',
        'ICAO': None,
        'Latitude': '29.388(N)',
        'FAA': None,
        'MaxRunway': '8990ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '74.158(E)',
        'ICAO': None,
        'Latitude': '17.286(N)',
        'FAA': None,
        'MaxRunway': '4200ft'
    },
    {
        'City': 'Kolhapur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Kolhapur',
        'IATA': 'KLH',
        'Longitude': '74.289(E)',
        'ICAO': 'VAKP',
        'Latitude': '16.665(N)',
        'FAA': None,
        'MaxRunway': '4495ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '74.611(E)',
        'ICAO': None,
        'Latitude': '25.141(N)',
        'FAA': None,
        'MaxRunway': '3895ft'
    },
    {
        'City': 'Bhatinda',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Bhatinda',
        'IATA': 'BUP',
        'Longitude': '74.756(E)',
        'ICAO': 'VIBT',
        'Latitude': '30.270(N)',
        'FAA': None,
        'MaxRunway': '9200ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '74.976(E)',
        'ICAO': 'VIAW',
        'Latitude': '33.877(N)',
        'FAA': None,
        'MaxRunway': '10500ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.006(E)',
        'ICAO': 'VISA',
        'Latitude': '29.561(N)',
        'FAA': None,
        'MaxRunway': '8987ft'
    },
    
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.156(E)',
        'ICAO': 'VIUX',
        'Latitude': '32.902(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.341(E)',
        'ICAO': None,
        'Latitude': '31.560(N)',
        'FAA': None,
        'MaxRunway': '4010ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.376(E)',
        'ICAO': None,
        'Latitude': '28.107(N)',
        'FAA': None,
        'MaxRunway': '4567ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.420(E)',
        'ICAO': None,
        'Latitude': '23.447(N)',
        'FAA': None,
        'MaxRunway': '4724ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.554(E)',
        'ICAO': None,
        'Latitude': '21.810(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.594(E)',
        'ICAO': None,
        'Latitude': '28.349(N)',
        'FAA': None,
        'MaxRunway': '3825ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.630(E)',
        'ICAO': 'VIHX',
        'Latitude': '30.749(N)',
        'FAA': None,
        'MaxRunway': '8985ft'
    },
    {
        'City': 'Pathankot',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Pathankot',
        'IATA': 'IXP',
        'Longitude': '75.635(E)',
        'ICAO': 'VIPK',
        'Latitude': '32.234(N)',
        'FAA': None,
        'MaxRunway': '8970ft'
    },
    {
        'City': 'Hissar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Hisar',
        'IATA': 'HSS',
        'Longitude': '75.755(E)',
        'ICAO': 'VIHR',
        'Latitude': '29.179(N)',
        'FAA': None,
        'MaxRunway': '4000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.759(E)',
        'ICAO': 'VIAX',
        'Latitude': '31.434(N)',
        'FAA': None,
        'MaxRunway': '9039ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '75.787(E)',
        'ICAO': None,
        'Latitude': '14.535(N)',
        'FAA': None,
        'MaxRunway': '4893ft'
    },
    {
        'City': 'Kota',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Kota',
        'IATA': 'KTU',
        'Longitude': '75.846(E)',
        'ICAO': 'VIKO',
        'Latitude': '25.160(N)',
        'FAA': None,
        'MaxRunway': '4078ft'
    },
    {
        'City': 'Ludhiana',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Ludhiana',
        'IATA': 'LUH',
        'Longitude': '75.953(E)',
        'ICAO': 'VILD',
        'Latitude': '30.855(N)',
        'FAA': None,
        'MaxRunway': '4615ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '76.156(E)',
        'ICAO': None,
        'Latitude': '34.524(N)',
        'FAA': None,
        'MaxRunway': '6004ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '76.179(E)',
        'ICAO': 'VIBW',
        'Latitude': '28.837(N)',
        'FAA': None,
        'MaxRunway': '3500ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '76.205(E)',
        'ICAO': None,
        'Latitude': '28.077(N)',
        'FAA': None,
        'MaxRunway': '3480ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '76.364(E)',
        'ICAO': 'VIPL',
        'Latitude': '30.315(N)',
        'FAA': None,
        'MaxRunway': '3830ft'
    },
    {
        'City': 'Toranagallu',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Toranagallu',
        'IATA': 'VDY',
        'Longitude': '76.635(E)',
        'ICAO': None,
        'Latitude': '15.175(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '76.817(E)',
        'ICAO': 'VIAM',
        'Latitude': '30.368(N)',
        'FAA': None,
        'MaxRunway': '9224ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '76.892(E)',
        'ICAO': None,
        'Latitude': '30.821(N)',
        'FAA': None,
        'MaxRunway': '3068ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.038(E)',
        'ICAO': None,
        'Latitude': '29.714(N)',
        'FAA': None,
        'MaxRunway': '3000ft'
    },
    {
        'City': 'Akola',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Akola',
        'IATA': 'AKD',
        'Longitude': '77.059(E)',
        'ICAO': 'VAAK',
        'Latitude': '20.699(N)',
        'FAA': None,
        'MaxRunway': '3985ft'
    },
    {
        'City': 'Shimla',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Shimla',
        'IATA': 'SLV',
        'Longitude': '77.068(E)',
        'ICAO': 'VISM',
        'Latitude': '31.082(N)',
        'FAA': None,
        'MaxRunway': '4035ft'
    },
    {
        'City': 'Kullu',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Chandigarh',
        'IATA': 'KUU',
        'Longitude': '77.154(E)',
        'ICAO': 'VIBR',
        'Latitude': '31.877(N)',
        'FAA': None,
        'MaxRunway': '3690ft'
    },
    {
        'City': 'Guna',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Guna',
        'IATA': 'GUX',
        'Longitude': '77.347(E)',
        'ICAO': 'VAGN',
        'Latitude': '24.655(N)',
        'FAA': None,
        'MaxRunway': '2982ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.359(E)',
        'ICAO': 'VIDX',
        'Latitude': '28.708(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.376(E)',
        'ICAO': None,
        'Latitude': '34.653(N)',
        'FAA': None,
        'MaxRunway': '10000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.425(E)',
        'ICAO': 'VISP',
        'Latitude': '29.994(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.487(E)',
        'ICAO': 'VOBR',
        'Latitude': '17.908(N)',
        'FAA': None,
        'MaxRunway': '6955ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.598(E)',
        'ICAO': None,
        'Latitude': '13.077(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.677(E)',
        'ICAO': None,
        'Latitude': '28.905(N)',
        'FAA': None,
        'MaxRunway': '5124ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.767(E)',
        'ICAO': None,
        'Latitude': '12.661(N)',
        'FAA': None,
        'MaxRunway': '3985ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.821(E)',
        'ICAO': None,
        'Latitude': '8.971(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.821(E)',
        'ICAO': None,
        'Latitude': '9.154(N)',
        'FAA': None,
        'MaxRunway': '3967ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '77.929(E)',
        'ICAO': None,
        'Latitude': '35.396(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Agra',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Agra',
        'IATA': 'AGR',
        'Longitude': '77.961(E)',
        'ICAO': 'VIAG',
        'Latitude': '27.156(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': 'Tuticorin',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Tuticorin',
        'IATA': 'TCR',
        'Longitude': '78.026(E)',
        'ICAO': None,
        'Latitude': '8.724(N)',
        'FAA': None,
        'MaxRunway': '4434ft'
    },
    {
        'City': 'Salem',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Salem',
        'IATA': 'SXV',
        'Longitude': '78.066(E)',
        'ICAO': 'VOSM',
        'Latitude': '11.783(N)',
        'FAA': None,
        'MaxRunway': '5925ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.114(E)',
        'ICAO': None,
        'Latitude': '21.926(N)',
        'FAA': None,
        'MaxRunway': '2279ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.262(E)',
        'ICAO': None,
        'Latitude': '26.000(N)',
        'FAA': None,
        'MaxRunway': '4027ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.323(E)',
        'ICAO': None,
        'Latitude': '30.583(N)',
        'FAA': None,
        'MaxRunway': '3285ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.525(E)',
        'ICAO': 'VOHK',
        'Latitude': '17.553(N)',
        'FAA': None,
        'MaxRunway': '6873ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.558(E)',
        'ICAO': 'VIJN',
        'Latitude': '25.491(N)',
        'FAA': None,
        'MaxRunway': '3630ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.560(E)',
        'ICAO': None,
        'Latitude': '17.306(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Cuddapah',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Cuddapah',
        'IATA': 'CDP',
        'Longitude': '78.773(E)',
        'ICAO': 'VOCP',
        'Latitude': '14.510(N)',
        'FAA': None,
        'MaxRunway': '3600ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.794(E)',
        'ICAO': None,
        'Latitude': '10.165(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.856(E)',
        'ICAO': None,
        'Latitude': '23.754(N)',
        'FAA': None,
        'MaxRunway': '3260ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.917(E)',
        'ICAO': None,
        'Latitude': '22.002(N)',
        'FAA': None,
        'MaxRunway': '3785ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.930(E)',
        'ICAO': None,
        'Latitude': '22.000(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '79.213(E)',
        'ICAO': None,
        'Latitude': '32.937(N)',
        'FAA': None,
        'MaxRunway': '9002ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '79.222(E)',
        'ICAO': None,
        'Latitude': '19.995(N)',
        'FAA': None,
        'MaxRunway': '3128ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '79.319(E)',
        'ICAO': 'VONS',
        'Latitude': '16.543(N)',
        'FAA': None,
        'MaxRunway': '5050ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '79.321(E)',
        'ICAO': None,
        'Latitude': '11.689(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Bareli',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Bareli',
        'IATA': 'BEK',
        'Longitude': '79.451(E)',
        'ICAO': 'VIBY',
        'Latitude': '28.422(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': 'Neyveli',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Vriddhachalam',
        'IATA': 'NVY',
        'Longitude': '79.527(E)',
        'ICAO': None,
        'Latitude': '11.613(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '79.691(E)',
        'ICAO': 'VOAR',
        'Latitude': '13.071(N)',
        'FAA': None,
        'MaxRunway': '12800ft'
    },
    {
        'City': 'Pondicherry',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Pondicherry',
        'IATA': 'PNY',
        'Longitude': '79.810(E)',
        'ICAO': 'VOPC',
        'Latitude': '11.969(N)',
        'FAA': None,
        'MaxRunway': '3983ft'
    },
    {
        'City': 'Jabalpur',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Jabalpur',
        'IATA': 'JLR',
        'Longitude': '80.052(E)',
        'ICAO': 'VAJB',
        'Latitude': '23.178(N)',
        'FAA': None,
        'MaxRunway': '6522ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '80.152(E)',
        'ICAO': None,
        'Latitude': '13.210(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '80.233(E)',
        'ICAO': None,
        'Latitude': '26.520(N)',
        'FAA': None,
        'MaxRunway': '2880ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '80.239(E)',
        'ICAO': 'VIDF',
        'Latitude': '29.594(N)',
        'FAA': None,
        'MaxRunway': '4335ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '80.290(E)',
        'ICAO': None,
        'Latitude': '21.526(N)',
        'FAA': None,
        'MaxRunway': '5625ft'
    },
    {
        'City': 'Kanpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Kanpur',
        'IATA': 'KNU',
        'Longitude': '80.365(E)',
        'ICAO': 'VIKA',
        'Latitude': '26.441(N)',
        'FAA': None,
        'MaxRunway': '2995ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '80.596(E)',
        'ICAO': None,
        'Latitude': '22.093(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Vijayawada',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Vijayawada',
        'IATA': 'VGA',
        'Longitude': '80.797(E)',
        'ICAO': 'VOBZ',
        'Latitude': '16.530(N)',
        'FAA': None,
        'MaxRunway': '5725ft'
    },
    {
        'City': 'Satna',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Satna',
        'IATA': 'TNI',
        'Longitude': '80.855(E)',
        'ICAO': 'VIST',
        'Latitude': '24.562(N)',
        'FAA': None,
        'MaxRunway': '3476ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '81.220(E)',
        'ICAO': None,
        'Latitude': '24.503(N)',
        'FAA': None,
        'MaxRunway': '3940ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '81.379(E)',
        'ICAO': None,
        'Latitude': '21.294(N)',
        'FAA': None,
        'MaxRunway': '3900ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '81.381(E)',
        'ICAO': 'VIRB',
        'Latitude': '26.248(N)',
        'FAA': None,
        'MaxRunway': '5650ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '81.504(E)',
        'ICAO': None,
        'Latitude': '23.235(N)',
        'FAA': None,
        'MaxRunway': '3670ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '81.815(E)',
        'ICAO': None,
        'Latitude': '24.402(N)',
        'FAA': None,
        'MaxRunway': '3540ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '82.043(E)',
        'ICAO': None,
        'Latitude': '26.247(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Bilaspur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Bilaspur',
        'IATA': 'PAB',
        'Longitude': '82.111(E)',
        'ICAO': 'VABI',
        'Latitude': '21.988(N)',
        'FAA': None,
        'MaxRunway': '5035ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '82.568(E)',
        'ICAO': None,
        'Latitude': '26.448(N)',
        'FAA': None,
        'MaxRunway': '4260ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '83.041(E)',
        'ICAO': None,
        'Latitude': '24.125(N)',
        'FAA': None,
        'MaxRunway': '4665ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '83.184(E)',
        'ICAO': 'VEUK',
        'Latitude': '20.097(N)',
        'FAA': None,
        'MaxRunway': '3000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '83.350(E)',
        'ICAO': None,
        'Latitude': '21.935(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '83.448(E)',
        'ICAO': None,
        'Latitude': '20.512(N)',
        'FAA': None,
        'MaxRunway': '4100ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '84.050(E)',
        'ICAO': 'VEJH',
        'Latitude': '21.914(N)',
        'FAA': None,
        'MaxRunway': '6320ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '84.095(E)',
        'ICAO': None,
        'Latitude': '24.019(N)',
        'FAA': None,
        'MaxRunway': '3000ft'
    },
    {
        'City': 'Rourkela',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Rourkela',
        'IATA': 'RRK',
        'Longitude': '84.815(E)',
        'ICAO': 'VERK',
        'Latitude': '22.257(N)',
        'FAA': None,
        'MaxRunway': '5542ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '84.833(E)',
        'ICAO': 'VERL',
        'Latitude': '26.967(N)',
        'FAA': None,
        'MaxRunway': '3600ft'
    },
    {
        'City': 'Gaya',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Gaya',
        'IATA': 'GAY',
        'Longitude': '84.951(E)',
        'ICAO': 'VEGY',
        'Latitude': '24.744(N)',
        'FAA': None,
        'MaxRunway': '7500ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '85.033(E)',
        'ICAO': None,
        'Latitude': '20.912(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Muzaffarpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Muzaffarpur',
        'IATA': 'MZU',
        'Longitude': '85.314(E)',
        'ICAO': 'VEMZ',
        'Latitude': '26.119(N)',
        'FAA': None,
        'MaxRunway': '3990ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '85.374(E)',
        'ICAO': None,
        'Latitude': '22.049(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '85.549(E)',
        'ICAO': None,
        'Latitude': '22.192(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '85.582(E)',
        'ICAO': 'VEKJ',
        'Latitude': '21.697(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '85.886(E)',
        'ICAO': None,
        'Latitude': '20.550(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '85.917(E)',
        'ICAO': None,
        'Latitude': '26.193(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '86.060(E)',
        'ICAO': None,
        'Latitude': '26.329(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Tatanagar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Tatanagar',
        'IATA': 'IXW',
        'Longitude': '86.169(E)',
        'ICAO': 'VEJS',
        'Latitude': '22.813(N)',
        'FAA': None,
        'MaxRunway': '3540ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '86.290(E)',
        'ICAO': None,
        'Latitude': '24.202(N)',
        'FAA': None,
        'MaxRunway': '3015ft'
    },
    {
        'City': 'Dhanbad',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Dhanbad',
        'IATA': 'DBD',
        'Longitude': '86.425(E)',
        'ICAO': 'VEDB',
        'Latitude': '23.834(N)',
        'FAA': None,
        'MaxRunway': '3728ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '86.708(E)',
        'ICAO': 'VECK',
        'Latitude': '22.461(N)',
        'FAA': None,
        'MaxRunway': '7200ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '86.976(E)',
        'ICAO': None,
        'Latitude': '23.631(N)',
        'FAA': None,
        'MaxRunway': '4010ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '87.010(E)',
        'ICAO': None,
        'Latitude': '25.249(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '87.107(E)',
        'ICAO': None,
        'Latitude': '22.325(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '87.214(E)',
        'ICAO': 'VEDX',
        'Latitude': '22.340(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '87.300(E)',
        'ICAO': None,
        'Latitude': '22.990(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '87.349(E)',
        'ICAO': None,
        'Latitude': '23.641(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '87.355(E)',
        'ICAO': None,
        'Latitude': '23.034(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '87.428(E)',
        'ICAO': 'VEPH',
        'Latitude': '23.474(N)',
        'FAA': None,
        'MaxRunway': '8700ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '87.794(E)',
        'ICAO': None,
        'Latitude': '23.472(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '88.587(E)',
        'ICAO': None,
        'Latitude': '27.231(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Cooch Behar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Cooch Behar',
        'IATA': 'COH',
        'Longitude': '89.467(E)',
        'ICAO': 'VECO',
        'Latitude': '26.331(N)',
        'FAA': None,
        'MaxRunway': '3500ft'
    },
    {
        'City': 'Rupsi',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Rupsa',
        'IATA': 'RUP',
        'Longitude': '89.910(E)',
        'ICAO': 'VERU',
        'Latitude': '26.140(N)',
        'FAA': None,
        'MaxRunway': '6000ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '90.345(E)',
        'ICAO': None,
        'Latitude': '25.661(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Kamalpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Bilaspur',
        'IATA': 'IXQ',
        'Longitude': '91.814(E)',
        'ICAO': 'VEKM',
        'Latitude': '24.132(N)',
        'FAA': None,
        'MaxRunway': '4500ft'
    },
    {
        'City': 'Kailashahar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'IXH',
        'Longitude': '92.007(E)',
        'ICAO': 'VEKR',
        'Latitude': '24.308(N)',
        'FAA': None,
        'MaxRunway': '3300ft'
    },
    {
        'City': 'Tezpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'TEZ',
        'Longitude': '92.785(E)',
        'ICAO': 'VETZ',
        'Latitude': '26.709(N)',
        'FAA': None,
        'MaxRunway': '9010ft'
    },
    {
        'City': 'Car Nicobar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': 'CBD',
        'Longitude': '92.820(E)',
        'ICAO': 'VOCX',
        'Latitude': '9.153(N)',
        'FAA': None,
        'MaxRunway': '8914ft'
    },
    {
        'City': 'Zero',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Dibrugarh',
        'IATA': 'ZER',
        'Longitude': '93.828(E)',
        'ICAO': 'VEZO',
        'Latitude': '27.588(N)',
        'FAA': None,
        'MaxRunway': '4010ft'
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '93.923(E)',
        'ICAO': None,
        'Latitude': '7.013(N)',
        'FAA': None,
        'MaxRunway': '3445ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '93.926(E)',
        'ICAO': None,
        'Latitude': '24.872(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '94.124(E)',
        'ICAO': None,
        'Latitude': '28.605(N)',
        'FAA': None,
        'MaxRunway': '4395ft'
    },
    {
        'City': 'Daparizo',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Dibrugarh',
        'IATA': 'DAE',
        'Longitude': '94.223(E)',
        'ICAO': 'VEDZ',
        'Latitude': '27.986(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Along',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Dibrugarh',
        'IATA': 'IXV',
        'Longitude': '94.802(E)',
        'ICAO': 'VEAN',
        'Latitude': '28.175(N)',
        'FAA': None,
        'MaxRunway': '915ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '95.269(E)',
        'ICAO': None,
        'Latitude': '27.538(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '95.571(E)',
        'ICAO': None,
        'Latitude': '27.553(N)',
        'FAA': None,
        'MaxRunway': '6595ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '95.737(E)',
        'ICAO': None,
        'Latitude': '27.302(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': None,
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '97.004(E)',
        'ICAO': None,
        'Latitude': '27.194(N)',
        'FAA': None,
        'MaxRunway': '3980ft'
    },
    {
        'City': None,
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '97.020(E)',
        'ICAO': None,
        'Latitude': '28.130(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'AambyValleyCity',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '73.378(E)',
        'ICAO': None,
        'Latitude': '18.610(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Agartala',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'IXA',
        'Longitude': '91.240(E)',
        'ICAO': 'VEAT',
        'Latitude': '23.887(N)',
        'FAA': None,
        'MaxRunway': '7500ft'
    },
    {
        'City': 'Ahmedabad',
        'Kind': 'Large',
        'Name': None,
        'RailwayStation': 'Ahmedabad',
        'IATA': 'AMD',
        'Longitude': '72.635(E)',
        'ICAO': 'VAAH',
        'Latitude': '23.077(N)',
        'FAA': None,
        'MaxRunway': '11447ft'
    },
    {
        'City': 'Aizwal',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'AJL',
        'Longitude': '92.620(E)',
        'ICAO': 'VELP',
        'Latitude': '23.841(N)',
        'FAA': None,
        'MaxRunway': '8202ft'
    },
    {
        'City': 'Aligarth',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '78.147(E)',
        'ICAO': 'VIAH',
        'Latitude': '27.861(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Allahabad',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Allahabad',
        'IATA': 'IXD',
        'Longitude': '81.734(E)',
        'ICAO': 'VIAL',
        'Latitude': '25.440(N)',
        'FAA': None,
        'MaxRunway': '8110ft'
    },
    {
        'City': 'Amravati',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Amravati',
        'IATA': None,
        'Longitude': '77.718(E)',
        'ICAO': None,
        'Latitude': '20.813(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Amreli',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Amreli',
        'IATA': None,
        'Longitude': '71.223(E)',
        'ICAO': None,
        'Latitude': '21.620(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Amritsar',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Amritsar',
        'IATA': 'ATQ',
        'Longitude': '74.797(E)',
        'ICAO': 'VIAR',
        'Latitude': '31.710(N)',
        'FAA': None,
        'MaxRunway': '10791ft'
    },
    {
        'City': 'Aurangabad',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Aurangabad',
        'IATA': 'IXU',
        'Longitude': '75.398(E)',
        'ICAO': 'VAAU',
        'Latitude': '19.863(N)',
        'FAA': None,
        'MaxRunway': '7713ft'
    },
    {
        'City': 'Balurghat',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Balurghat',
        'IATA': 'RGH',
        'Longitude': '88.796(E)',
        'ICAO': 'VEBG',
        'Latitude': '25.262(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Bangalore',
        'Kind': 'Large',
        'Name': None,
        'RailwayStation': 'Bangalore',
        'IATA': 'BLR',
        'Longitude': '77.706(E)',
        'ICAO': 'VOBL',
        'Latitude': '13.198(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Barrackpore',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Barrackpore',
        'IATA': None,
        'Longitude': '88.359(E)',
        'ICAO': None,
        'Latitude': '22.781(N)',
        'FAA': None,
        'MaxRunway': '6116ft'
    },
    {
        'City': 'Behala',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Behala',
        'IATA': None,
        'Longitude': '88.293(E)',
        'ICAO': 'VEBA',
        'Latitude': '22.504(N)',
        'FAA': None,
        'MaxRunway': '2800ft'
    },
    {
        'City': 'Belgaum',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Belgaum',
        'IATA': 'IXG',
        'Longitude': '74.618(E)',
        'ICAO': 'VABM',
        'Latitude': '15.859(N)',
        'FAA': None,
        'MaxRunway': '4786ft'
    },
    {
        'City': 'Bellary',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Bellary',
        'IATA': 'BEP',
        'Longitude': '76.883(E)',
        'ICAO': 'VOBI',
        'Latitude': '15.163(N)',
        'FAA': None,
        'MaxRunway': '3630ft'
    },
    {
        'City': 'Bhavnagar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Bhavnagar',
        'IATA': 'BHU',
        'Longitude': '72.185(E)',
        'ICAO': 'VABV',
        'Latitude': '21.752(N)',
        'FAA': None,
        'MaxRunway': '6300ft'
    },
    {
        'City': 'Bhopal',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Bhopal',
        'IATA': 'BHO',
        'Longitude': '77.337(E)',
        'ICAO': 'VABP',
        'Latitude': '23.287(N)',
        'FAA': None,
        'MaxRunway': '6700ft'
    },
    {
        'City': 'Bhubaneswar',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Bhubaneswar',
        'IATA': 'BBI',
        'Longitude': '85.818(E)',
        'ICAO': 'VEBS',
        'Latitude': '20.244(N)',
        'FAA': None,
        'MaxRunway': '7359ft'
    },
    {
        'City': 'Bhuj',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Bhuj',
        'IATA': 'BHJ',
        'Longitude': '69.670(E)',
        'ICAO': 'VABJ',
        'Latitude': '23.288(N)',
        'FAA': None,
        'MaxRunway': '8205ft'
    },
    {
        'City': 'Bikaner',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Bikaner',
        'IATA': 'BKB',
        'Longitude': '73.207(E)',
        'ICAO': 'VIBK',
        'Latitude': '28.071(N)',
        'FAA': None,
        'MaxRunway': '8960ft'
    },
    {
        'City': 'Chandigarh',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Chandigarh',
        'IATA': 'IXC',
        'Longitude': '76.789(E)',
        'ICAO': 'VICG',
        'Latitude': '30.673(N)',
        'FAA': None,
        'MaxRunway': '9001ft'
    },
    {
        'City': 'Chennai',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Chennai',
        'IATA': None,
        'Longitude': '80.122(E)',
        'ICAO': 'VOTX',
        'Latitude': '12.907(N)',
        'FAA': None,
        'MaxRunway': '5965ft'
    },
    {
        'City': 'Cochin',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Kochi',
        'IATA': 'COK',
        'Longitude': '76.402(E)',
        'ICAO': 'VOCI',
        'Latitude': '10.152(N)',
        'FAA': None,
        'MaxRunway': '11155ft'
    },
    {
        'City': 'Coimbatore',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Coimbatore',
        'IATA': 'CJB',
        'Longitude': '77.043(E)',
        'ICAO': 'VOCB',
        'Latitude': '11.030(N)',
        'FAA': None,
        'MaxRunway': '8480ft'
    },
    {
        'City': 'Dabolim',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Goa',
        'IATA': 'GOI',
        'Longitude': '73.831(E)',
        'ICAO': 'VAGO',
        'Latitude': '15.381(N)',
        'FAA': None,
        'MaxRunway': '11345ft'
    },
    {
        'City': 'Dehradun',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Dehradun',
        'IATA': 'DED',
        'Longitude': '78.180(E)',
        'ICAO': 'VIDN',
        'Latitude': '30.190(N)',
        'FAA': None,
        'MaxRunway': '3405ft'
    },
    {
        'City': 'Delhi',
        'Kind': 'Large',
        'Name': None,
        'RailwayStation': 'New Delhi',
        'IATA': 'DEL',
        'Longitude': '77.103(E)',
        'ICAO': 'VIDP',
        'Latitude': '28.567(N)',
        'FAA': None,
        'MaxRunway': '12500ft'
    },
    {
        'City': 'Dhubulia',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Dhubulia',
        'IATA': None,
        'Longitude': '88.454(E)',
        'ICAO': None,
        'Latitude': '23.493(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Dibrugarh',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Dibrugarh',
        'IATA': 'DIB',
        'Longitude': '95.017(E)',
        'ICAO': 'VEMN',
        'Latitude': '27.484(N)',
        'FAA': None,
        'MaxRunway': '6000ft'
    },
    {
        'City': 'Dibrugarh',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Dibrugarh',
        'IATA': None,
        'Longitude': '95.118(E)',
        'ICAO': 'VECA',
        'Latitude': '27.462(N)',
        'FAA': None,
        'MaxRunway': '9003ft'
    },
    {
        'City': 'Digri',
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': 'Kolkata',
        'IATA': None,
        'Longitude': '87.362(E)',
        'ICAO': None,
        'Latitude': '22.785(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Dimapur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Dimapur',
        'IATA': 'DMU',
        'Longitude': '93.771(E)',
        'ICAO': 'VEMR',
        'Latitude': '25.884(N)',
        'FAA': None,
        'MaxRunway': '7513ft'
    },
    {
        'City': 'Diu',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Rajkot',
        'IATA': 'DIU',
        'Longitude': '70.921(E)',
        'ICAO': None,
        'Latitude': '20.713(N)',
        'FAA': None,
        'MaxRunway': '5980ft'
    },
    {
        'City': 'Dunakonda',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '79.500(E)',
        'ICAO': 'VODK',
        'Latitude': '15.833(N)',
        'FAA': None,
        'MaxRunway': '3000ft'
    },
    {
        'City': 'Faizabad',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Faizabad',
        'IATA': None,
        'Longitude': '82.154(E)',
        'ICAO': None,
        'Latitude': '26.751(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Gaggal',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Pathankot',
        'IATA': 'DHM',
        'Longitude': '76.263(E)',
        'ICAO': 'VIGG',
        'Latitude': '32.165(N)',
        'FAA': None,
        'MaxRunway': '4620ft'
    },
    {
        'City': 'Gorakhpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Gorakhpur',
        'IATA': 'GOP',
        'Longitude': '83.450(E)',
        'ICAO': 'VEGK',
        'Latitude': '26.740(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': 'Guwahati',
        'Kind': 'Large',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'GAU',
        'Longitude': '91.586(E)',
        'ICAO': 'VEGT',
        'Latitude': '26.106(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': 'Gwalior',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Gwalior',
        'IATA': 'GWL',
        'Longitude': '78.228(E)',
        'ICAO': 'VIGR',
        'Latitude': '26.293(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': 'Hospete',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Anantapur',
        'IATA': None,
        'Longitude': '76.517(E)',
        'ICAO': None,
        'Latitude': '15.358(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Hubli',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Hubli',
        'IATA': 'HBX',
        'Longitude': '75.085(E)',
        'ICAO': 'VAHB',
        'Latitude': '15.362(N)',
        'FAA': None,
        'MaxRunway': '5304ft'
    },
    {
        'City': 'Hyderabad',
        'Kind': 'Large',
        'Name': None,
        'RailwayStation': 'Hyderabad',
        'IATA': 'HYD',
        'Longitude': '78.430(E)',
        'ICAO': 'VOHS',
        'Latitude': '17.231(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Imphal',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'IMF',
        'Longitude': '93.897(E)',
        'ICAO': 'VEIM',
        'Latitude': '24.760(N)',
        'FAA': None,
        'MaxRunway': '9009ft'
    },
    {
        'City': 'Indore',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Indore',
        'IATA': 'IDR',
        'Longitude': '75.801(E)',
        'ICAO': 'VAID',
        'Latitude': '22.722(N)',
        'FAA': None,
        'MaxRunway': '7480ft'
    },
    {
        'City': 'Jagdalpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Jagdalpur',
        'IATA': 'JGB',
        'Longitude': '82.037(E)',
        'ICAO': None,
        'Latitude': '19.074(N)',
        'FAA': None,
        'MaxRunway': '5600ft'
    },
    {
        'City': 'Jaipur',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Jaipur',
        'IATA': 'JAI',
        'Longitude': '75.812(E)',
        'ICAO': 'VIJP',
        'Latitude': '26.824(N)',
        'FAA': None,
        'MaxRunway': '9177ft'
    },
    {
        'City': 'Jalpaiguri',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Jalpaiguri',
        'IATA': None,
        'Longitude': '89.369(E)',
        'ICAO': None,
        'Latitude': '26.698(N)',
        'FAA': None,
        'MaxRunway': '9000ft'
    },
    {
        'City': 'Jammu',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Jammu',
        'IATA': 'IXJ',
        'Longitude': '74.837(E)',
        'ICAO': 'VIJU',
        'Latitude': '32.689(N)',
        'FAA': None,
        'MaxRunway': '6555ft'
    },
    {
        'City': 'Jamnagar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Jamnagar',
        'IATA': 'JGA',
        'Longitude': '70.013(E)',
        'ICAO': 'VAJM',
        'Latitude': '22.466(N)',
        'FAA': None,
        'MaxRunway': '8242ft'
    },
    {
        'City': 'Jeypore',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Jeypore',
        'IATA': 'PYB',
        'Longitude': '82.552(E)',
        'ICAO': 'VEJP',
        'Latitude': '18.880(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Jodhpur',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Jodhpur',
        'IATA': 'JDH',
        'Longitude': '73.049(E)',
        'ICAO': 'VIJO',
        'Latitude': '26.251(N)',
        'FAA': None,
        'MaxRunway': '9005ft'
    },
    {
        'City': 'Jorhat',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Jorhat',
        'IATA': 'JRH',
        'Longitude': '94.176(E)',
        'ICAO': 'VEJT',
        'Latitude': '26.732(N)',
        'FAA': None,
        'MaxRunway': '8875ft'
    },
    {
        'City': 'Kalyan',
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '73.139(E)',
        'ICAO': None,
        'Latitude': '19.179(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Kanchrapara',
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '88.460(E)',
        'ICAO': None,
        'Latitude': '22.923(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Kandla',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Gandhidham',
        'IATA': 'IXY',
        'Longitude': '70.100(E)',
        'ICAO': 'VAKE',
        'Latitude': '23.113(N)',
        'FAA': None,
        'MaxRunway': '4997ft'
    },
    {
        'City': 'Kanpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Kanpur',
        'IATA': None,
        'Longitude': '80.410(E)',
        'ICAO': 'VICX',
        'Latitude': '26.404(N)',
        'FAA': None,
        'MaxRunway': '8216ft'
    },
    {
        'City': 'Kozhikode',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Kozhikode',
        'IATA': 'CCJ',
        'Longitude': '75.955(E)',
        'ICAO': 'VOCL',
        'Latitude': '11.137(N)',
        'FAA': None,
        'MaxRunway': '9383ft'
    },
    {
        'City': 'Khajuraho',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Khajuraho',
        'IATA': 'HJR',
        'Longitude': '79.919(E)',
        'ICAO': 'VAKJ',
        'Latitude': '24.817(N)',
        'FAA': None,
        'MaxRunway': '7460ft'
    },
    {
        'City': 'Khandwa',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Khandwa',
        'IATA': None,
        'Longitude': '76.337(E)',
        'ICAO': None,
        'Latitude': '21.857(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Khowai',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'IXN',
        'Longitude': '91.604(E)',
        'ICAO': 'VEKW',
        'Latitude': '24.062(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Kochi',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Kochi',
        'IATA': None,
        'Longitude': '76.273(E)',
        'ICAO': 'VOCC',
        'Latitude': '9.947(N)',
        'FAA': None,
        'MaxRunway': '5620ft'
    },
    {
        'City': 'Kolkata',
        'Kind': 'Large',
        'Name': None,
        'RailwayStation': 'Kolkata',
        'IATA': 'CCU',
        'Longitude': '88.447(E)',
        'ICAO': 'VECC',
        'Latitude': '22.655(N)',
        'FAA': None,
        'MaxRunway': '11900ft'
    },
    {
        'City': 'Koppal',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Koppal',
        'IATA': None,
        'Longitude': '76.220(E)',
        'ICAO': None,
        'Latitude': '15.360(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Kumbhigram',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'IXS',
        'Longitude': '92.979(E)',
        'ICAO': 'VEKU',
        'Latitude': '24.913(N)',
        'FAA': None,
        'MaxRunway': '5993ft'
    },
    {
        'City': 'Lalitpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Lalitpur',
        'IATA': None,
        'Longitude': '78.417(E)',
        'ICAO': 'VILP',
        'Latitude': '24.717(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Latur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Latur',
        'IATA': 'LTU',
        'Longitude': '76.465(E)',
        'ICAO': None,
        'Latitude': '18.411(N)',
        'FAA': None,
        'MaxRunway': '5260ft'
    },
    {
        'City': 'Leh',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Jammu',
        'IATA': 'IXL',
        'Longitude': '77.547(E)',
        'ICAO': 'VILH',
        'Latitude': '34.136(N)',
        'FAA': None,
        'MaxRunway': '9040ft'
    },
    {
        'City': 'Lucknow',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Lucknow',
        'IATA': 'LKO',
        'Longitude': '80.889(E)',
        'ICAO': 'VILK',
        'Latitude': '26.761(N)',
        'FAA': None,
        'MaxRunway': '8996ft'
    },
    {
        'City': 'Lucknow',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Lucknow',
        'IATA': None,
        'Longitude': '80.893(E)',
        'ICAO': 'VIBL',
        'Latitude': '26.988(N)',
        'FAA': None,
        'MaxRunway': '8990ft'
    },
    {
        'City': 'Madhupur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Madhupur',
        'IATA': None,
        'Longitude': '93.050(E)',
        'ICAO': None,
        'Latitude': '13.236(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Madras',
        'Kind': 'Large',
        'Name': None,
        'RailwayStation': 'Chennai',
        'IATA': 'MAA',
        'Longitude': '80.181(E)',
        'ICAO': 'VOMM',
        'Latitude': '12.994(N)',
        'FAA': None,
        'MaxRunway': '12001ft'
    },
    {
        'City': 'Madurai',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Madurai',
        'IATA': 'IXM',
        'Longitude': '78.093(E)',
        'ICAO': 'VOMD',
        'Latitude': '9.835(N)',
        'FAA': None,
        'MaxRunway': '5990ft'
    },
    {
        'City': 'Malda',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Malda',
        'IATA': 'LDA',
        'Longitude': '88.133(E)',
        'ICAO': 'VEMH',
        'Latitude': '25.033(N)',
        'FAA': None,
        'MaxRunway': '3600ft'
    },
    {
        'City': 'Mangalore',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Mangalore',
        'IATA': 'IXE',
        'Longitude': '74.890(E)',
        'ICAO': 'VOML',
        'Latitude': '12.961(N)',
        'FAA': None,
        'MaxRunway': '5300ft'
    },
    {
        'City': 'Maraphari',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '86.149(E)',
        'ICAO': 'VEBK',
        'Latitude': '23.643(N)',
        'FAA': None,
        'MaxRunway': '5300ft'
    },
    {
        'City': 'Mumbai',
        'Kind': 'Large',
        'Name': None,
        'RailwayStation': 'Mumbai',
        'IATA': 'BOM',
        'Longitude': '72.868(E)',
        'ICAO': 'VABB',
        'Latitude': '19.089(N)',
        'FAA': None,
        'MaxRunway': '10837ft'
    },
    {
        'City': 'Mysore',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Mysore',
        'IATA': 'MYQ',
        'Longitude': '76.650(E)',
        'ICAO': 'VOMY',
        'Latitude': '12.307(N)',
        'FAA': None,
        'MaxRunway': '4400ft'
    },
    {
        'City': 'Nagpur',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Nagpur',
        'IATA': 'NAG',
        'Longitude': '79.047(E)',
        'ICAO': 'VANP',
        'Latitude': '21.092(N)',
        'FAA': None,
        'MaxRunway': '10500ft'
    },
    {
        'City': 'Nanded',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Nanded',
        'IATA': 'NDC',
        'Longitude': '77.318(E)',
        'ICAO': None,
        'Latitude': '19.182(N)',
        'FAA': None,
        'MaxRunway': '4510ft'
    },
    {
        'City': 'Nashik',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Nashik',
        'IATA': 'ISK',
        'Longitude': '73.808(E)',
        'ICAO': 'VANR',
        'Latitude': '19.964(N)',
        'FAA': None,
        'MaxRunway': '4520ft'
    },
    {
        'City': 'Nawapara',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Nawapara',
        'IATA': None,
        'Longitude': '82.520(E)',
        'ICAO': 'VENP',
        'Latitude': '20.870(N)',
        'FAA': None,
        'MaxRunway': '3380ft'
    },
    {
        'City': 'NorthLakhimpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'IXI',
        'Longitude': '94.098(E)',
        'ICAO': 'VELR',
        'Latitude': '27.295(N)',
        'FAA': None,
        'MaxRunway': '7500ft'
    },
    {
        'City': 'Pantnagar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Pantnagar',
        'IATA': 'PGH',
        'Longitude': '79.474(E)',
        'ICAO': 'VIPT',
        'Latitude': '29.033(N)',
        'FAA': None,
        'MaxRunway': '3600ft'
    },
    {
        'City': 'Pasighat',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Dibrugarh',
        'IATA': 'IXT',
        'Longitude': '95.336(E)',
        'ICAO': 'VEPG',
        'Latitude': '28.066(N)',
        'FAA': None,
        'MaxRunway': '3300ft'
    },
    {
        'City': 'Patna',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Patna',
        'IATA': 'PAT',
        'Longitude': '85.088(E)',
        'ICAO': 'VEPT',
        'Latitude': '25.591(N)',
        'FAA': None,
        'MaxRunway': '5970ft'
    },
    {
        'City': 'Phalodi',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Phalodi',
        'IATA': None,
        'Longitude': '72.389(E)',
        'ICAO': None,
        'Latitude': '27.113(N)',
        'FAA': None,
        'MaxRunway': '3565ft'
    },
    {
        'City': 'Porbandar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Porbandar',
        'IATA': 'PBD',
        'Longitude': '69.657(E)',
        'ICAO': 'VAPR',
        'Latitude': '21.649(N)',
        'FAA': None,
        'MaxRunway': '4500ft'
    },
    {
        'City': 'PortBlair',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': None,
        'IATA': 'IXZ',
        'Longitude': '92.730(E)',
        'ICAO': 'VOPB',
        'Latitude': '11.641(N)',
        'FAA': None,
        'MaxRunway': '10795ft'
    },
    {
        'City': 'Prasanthinilayam',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'New Delhi',
        'IATA': 'PUT',
        'Longitude': '77.791(E)',
        'ICAO': 'VOPN',
        'Latitude': '14.149(N)',
        'FAA': None,
        'MaxRunway': '7315ft'
    },
    {
        'City': 'Pune',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Pune',
        'IATA': 'PNQ',
        'Longitude': '73.920(E)',
        'ICAO': 'VAPO',
        'Latitude': '18.582(N)',
        'FAA': None,
        'MaxRunway': '8329ft'
    },
    {
        'City': 'Pune',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Pune',
        'IATA': None,
        'Longitude': '74.591(E)',
        'ICAO': None,
        'Latitude': '18.227(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Purulia',
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': 'Purulia',
        'IATA': None,
        'Longitude': '86.437(E)',
        'ICAO': None,
        'Latitude': '23.366(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Raipur',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Raipur',
        'IATA': 'RPR',
        'Longitude': '81.739(E)',
        'ICAO': 'VARP',
        'Latitude': '21.180(N)',
        'FAA': None,
        'MaxRunway': '6414ft'
    },
    {
        'City': 'Rajahmundry',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Rajahmundry',
        'IATA': 'RJA',
        'Longitude': '81.818(E)',
        'ICAO': 'VORY',
        'Latitude': '17.110(N)',
        'FAA': None,
        'MaxRunway': '5710ft'
    },
    {
        'City': 'Rajkot',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Rajkot',
        'IATA': 'RAJ',
        'Longitude': '70.780(E)',
        'ICAO': 'VARK',
        'Latitude': '22.309(N)',
        'FAA': None,
        'MaxRunway': '5740ft'
    },
    {
        'City': 'Rajouri',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Jammu',
        'IATA': None,
        'Longitude': '74.315(E)',
        'ICAO': None,
        'Latitude': '33.378(N)',
        'FAA': None,
        'MaxRunway': '3300ft'
    },
    {
        'City': 'Ramnad',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Tiruchirappalli',
        'IATA': None,
        'Longitude': '78.971(E)',
        'ICAO': 'VORM',
        'Latitude': '9.325(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Ranchi',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Ranchi',
        'IATA': 'IXR',
        'Longitude': '85.322(E)',
        'ICAO': 'VERC',
        'Latitude': '23.314(N)',
        'FAA': None,
        'MaxRunway': '8855ft'
    },
    {
        'City': 'Rasgovindpur',
        'Kind': 'Closed',
        'Name': None,
        'RailwayStation': 'Kharagpur',
        'IATA': None,
        'Longitude': '87.047(E)',
        'ICAO': None,
        'Latitude': '21.805(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Rumgara',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Bilaspur',
        'IATA': None,
        'Longitude': '82.719(E)',
        'ICAO': None,
        'Latitude': '22.414(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Sambalpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Sambalpur',
        'IATA': None,
        'Longitude': '84.006(E)',
        'ICAO': 'VEHK',
        'Latitude': '21.580(N)',
        'FAA': None,
        'MaxRunway': '4185ft'
    },
    {
        'City': 'Shillong',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Guwahati',
        'IATA': 'SHL',
        'Longitude': '91.979(E)',
        'ICAO': 'VEBI',
        'Latitude': '25.704(N)',
        'FAA': None,
        'MaxRunway': '6000ft'
    },
    {
        'City': 'Shirpur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Manmad',
        'IATA': None,
        'Longitude': '74.957(E)',
        'ICAO': None,
        'Latitude': '21.324(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Siliguri',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'New Jalpaiguri',
        'IATA': 'IXB',
        'Longitude': '88.329(E)',
        'ICAO': 'VEBD',
        'Latitude': '26.681(N)',
        'FAA': None,
        'MaxRunway': '9035ft'
    },
    {
        'City': 'Solapur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Solapur',
        'IATA': 'SSE',
        'Longitude': '75.935(E)',
        'ICAO': 'VASL',
        'Latitude': '17.628(N)',
        'FAA': None,
        'MaxRunway': '4472ft'
    },
    {
        'City': 'Srinagar',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Jammu',
        'IATA': 'SXR',
        'Longitude': '74.774(E)',
        'ICAO': 'VISR',
        'Latitude': '33.987(N)',
        'FAA': None,
        'MaxRunway': '12090ft'
    },
    {
        'City': 'Sulur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Coimbatore',
        'IATA': None,
        'Longitude': '77.160(E)',
        'ICAO': 'VOSX',
        'Latitude': '11.014(N)',
        'FAA': None,
        'MaxRunway': '8255ft'
    },
    {
        'City': 'Tezu',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Dibrugarh',
        'IATA': 'TEI',
        'Longitude': '96.134(E)',
        'ICAO': None,
        'Latitude': '27.941(N)',
        'FAA': None,
        'MaxRunway': '4505ft'
    },
    {
        'City': 'Thanjavur',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Thanjavur',
        'IATA': 'TJV',
        'Longitude': '79.102(E)',
        'ICAO': 'VOTJ',
        'Latitude': '10.722(N)',
        'FAA': None,
        'MaxRunway': '5680ft'
    },
    {
        'City': 'Tiruchirappally',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Tiruchirappally',
        'IATA': 'TRZ',
        'Longitude': '78.710(E)',
        'ICAO': 'VOTR',
        'Latitude': '10.765(N)',
        'FAA': None,
        'MaxRunway': '6115ft'
    },
    {
        'City': 'Tirupati',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Tirupati',
        'IATA': 'TIR',
        'Longitude': '79.543(E)',
        'ICAO': 'VOTP',
        'Latitude': '13.632(N)',
        'FAA': None,
        'MaxRunway': '7500ft'
    },
    {
        'City': 'Trivandrum',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Trivandrum',
        'IATA': 'TRV',
        'Longitude': '76.920(E)',
        'ICAO': 'VOTV',
        'Latitude': '8.482(N)',
        'FAA': None,
        'MaxRunway': '10626ft'
    },
    {
        'City': 'Udaipur',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Udaipur',
        'IATA': 'UDR',
        'Longitude': '73.896(E)',
        'ICAO': 'VAUD',
        'Latitude': '24.618(N)',
        'FAA': None,
        'MaxRunway': '7484ft'
    },
    {
        'City': 'Ujjain',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Ujjain',
        'IATA': None,
        'Longitude': '75.885(E)',
        'ICAO': None,
        'Latitude': '23.095(N)',
        'FAA': None,
        'MaxRunway': '3491ft'
    },
    {
        'City': 'Umaria',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Umaria',
        'IATA': None,
        'Longitude': '80.808(E)',
        'ICAO': None,
        'Latitude': '23.533(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Vadodara',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Vadodara',
        'IATA': 'BDQ',
        'Longitude': '73.226(E)',
        'ICAO': 'VABO',
        'Latitude': '22.336(N)',
        'FAA': None,
        'MaxRunway': '8100ft'
    },
    {
        'City': 'Varanasi',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Varanasi',
        'IATA': 'VNS',
        'Longitude': '82.859(E)',
        'ICAO': 'VIBN',
        'Latitude': '25.452(N)',
        'FAA': None,
        'MaxRunway': '7238ft'
    },
    {
        'City': 'Vellore',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Vellore',
        'IATA': None,
        'Longitude': '79.067(E)',
        'ICAO': 'VOVR',
        'Latitude': '12.909(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'VijayNagar',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': None,
        'IATA': None,
        'Longitude': '73.841(E)',
        'ICAO': None,
        'Latitude': '19.884(N)',
        'FAA': None,
        'MaxRunway': None
    },
    {
        'City': 'Visakhapatnam',
        'Kind': 'Medium',
        'Name': None,
        'RailwayStation': 'Visakhapatnam',
        'IATA': 'VTZ',
        'Longitude': '83.224(E)',
        'ICAO': 'VEVZ',
        'Latitude': '17.721(N)',
        'FAA': None,
        'MaxRunway': '6000ft'
    },
    {
        'City': 'Warrangal',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Warrangal',
        'IATA': 'WGC',
        'Longitude': '79.602(E)',
        'ICAO': 'VOWA',
        'Latitude': '17.914(N)',
        'FAA': None,
        'MaxRunway': '5700ft'
    },
    {
        'City': 'Yelahanka',
        'Kind': 'Small',
        'Name': None,
        'RailwayStation': 'Bangalore',
        'IATA': None,
        'Longitude': '77.606(E)',
        'ICAO': 'VOYK',
        'Latitude': '13.136(N)',
        'FAA': None,
        'MaxRunway': '6690ft'
    }]


def findnearestairport(latitude, longitude):
    minimumdistance = 0.0
    sourceplace = (latitude, longitude)
    nearestairport = ""
    for airport in airportlist:
        airlatitude = airport["Latitude"]
        airlatitude = airlatitude[:-3]
        distance = vincenty((float(airlatitude), float(airport["Longitude"][:-3])), sourceplace)
        if airport["IATA"] and airport["Kind"] != "Small" and airport["Kind"] != "Closed":
            if minimumdistance == 0.0:
                minimumdistance = distance
                nearestairport = airport["IATA"]
            if distance < minimumdistance:
                minimumdistance = distance
                nearestairport = airport["IATA"]
    return nearestairport


def findnearestbigairport(latitude, longitude):
    minimumdistance = 0.0
    sourceplace = (latitude, longitude)
    nearestairport = ""
    for airport in airportlist:
        airlatitude = airport["Latitude"]
        airlatitude = airlatitude[:-3]
        distance = vincenty((float(airlatitude), float(airport["Longitude"][:-3])), sourceplace)
        if airport["IATA"] and airport["Kind"] == "Large":
            if minimumdistance == 0.0:
                minimumdistance = distance
                nearestairport = airport["IATA"]
            elif distance < minimumdistance:
                minimumdistance = distance
                nearestairport = airport["IATA"]
    return nearestairport


"""def parse():

    table = etree.XML(sdd.s)
    rows = iter(table)
    listairport=[]
    headers = [col.text for col in next(rows)]
    for row in rows:
        values = [col.text for col in row]
        listairport.append(dict(zip(headers, values)))

  print(listairport)"""


def findnearestrailwaystation(latitude, longitude, cityname):
    """
    To find nearest city with railway station to our city
    :param latitude: latitude of city
    :param longitude: longitude of city
    :param cityname: name of the city
    :return: name of nearest city with railway
    """
    
    mindistance = 0.0
    sourceplace = (latitude, longitude)
    nearestrailstation = ""
    for airport in airportlist:
        if airport["RailwayStation"] and cityname.upper() != airport["RailwayStation"].upper():
            airlatitude = airport["Latitude"]
            airlatitude = airlatitude[:-3]
            distance = vincenty((float(airlatitude), float(airport["Longitude"][:-3])), sourceplace)
            if mindistance == 0.0:
                mindistance = distance
                nearestrailstation = airport["RailwayStation"]
            elif distance < mindistance:
                mindistance = distance
                nearestrailstation = airport["RailwayStation"]

    return nearestrailstation
